parameters:
  - name: pushImage
    displayName: 'Push image to registry'
    default: master-only
    values:
    - master-only
    - force
  - name: deployAzureContainerAppEnv
    displayName: 'Deploy azure container app'
    default: none
    values:
    - none
    - prod

trigger:
  branches:
    include:
    - adam
  paths:
    include:
    - src/TaylorBot.Net
    - src/taylorbot-postgres/sqitch
    - src/slash-commands

pr:
  branches:
    include:
    - master
  paths:
    include:
    - src/TaylorBot.Net
    - src/taylorbot-postgres/sqitch
    - src/slash-commands

resources:
- repo: self

variables:
  DOCKER_BUILDKIT: 1

stages:
- template: ../build-test-publish-dotnet-docker.yml
  parameters:
    componentName: commands-discord
    dockerfilePath: '$(Build.SourcesDirectory)/src/TaylorBot.Net/Program.Commands.Discord/Dockerfile'
    dockerBuildContext: '$(Build.SourcesDirectory)/src/TaylorBot.Net'
    deployAzureContainerScript: src/TaylorBot.Net/Program.Commands.Discord/Deploy-CommandsDiscord.ps1
    integrationTestProject: '$(Build.SourcesDirectory)/src/TaylorBot.Net/Program.Commands.Discord/test/TaylorBot.Net.Commands.Discord.IntegrationTests/TaylorBot.Net.Commands.Discord.IntegrationTests.csproj'
    pushImage: ${{ parameters.pushImage }}
    deployAzureContainerAppEnv: ${{ parameters.deployAzureContainerAppEnv }}
