<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="coverlet.collector" PrivateAssets="all" />
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Testcontainers.PostgreSql" />
    <PackageReference Include="Testcontainers.Redis" />
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="xunit.runner.visualstudio" PrivateAssets="all" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\TaylorBot.Net.Commands.Discord.Program\TaylorBot.Net.Commands.Discord.Program.csproj" />
    <None Include="..\..\..\..\taylorbot-postgres\sqitch\**\*" Link="Fixtures\Sqitch\%(RecursiveDir)%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" />
    <None Include="..\..\..\..\slash-commands\*.json" Link="Fixtures\Commands\%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" />
    <None Include="..\..\..\..\slash-commands\guilds\**\*.json" Link="Fixtures\Commands\guilds\%(RecursiveDir)%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
