parameters:
  - name: pushImage
    displayName: 'Push image to registry'
    default: master-only
    values:
    - master-only
    - force
  - name: deployAzureContainerAppEnv
    displayName: 'Deploy azure container app'
    default: none
    values:
    - none
    - prod

trigger:
  branches:
    include:
    - adam
  paths:
    include:
    - src/TaylorBot.Net

pr:
  branches:
    include:
    - master
  paths:
    include:
    - src/TaylorBot.Net

resources:
- repo: self

variables:
  DOCKER_BUILDKIT: 1

stages:
- template: ../build-test-publish-dotnet-docker.yml
  parameters:
    componentName: entity-tracker
    dockerfilePath: '$(Build.SourcesDirectory)/src/TaylorBot.Net/Program.EntityTracker/Dockerfile'
    dockerBuildContext: '$(Build.SourcesDirectory)/src/TaylorBot.Net'
    deployAzureContainerScript: src/TaylorBot.Net/Program.EntityTracker/Deploy-EntityTracker.ps1
    pushImage: ${{ parameters.pushImage }}
    deployAzureContainerAppEnv: ${{ parameters.deployAzureContainerAppEnv }}
